### ISSUE TITLE
Install fails due to broken typescript-require 0.2.8 dependency

### ISSUE THREAD

**Issue by nolanlawson** [jednano/bombom#1]
Steps to repro:

```
npm install bombom
```

Result:

> npm ERR! Error extracting /tmp/npm/.npm/typescript-require/0.2.8/package.tgz archive: ENOENT: no such file or directory, open '/tmp/npm/.npm/typescript-require/0.2.8/package.tgz'

Seems it's related to https://github.com/theblacksmith/typescript-require/issues/39.

One nice solution would be if this module did the typescript compilation as a `prepublish` step rather than having dependents do the typescript compilation on their machine.

**Comment by jednano** [comment]
Fixed in https://github.com/jedmao/bombom/commit/77a5c653da034f1ca36d2e266107704e77bfdc3b and published as v0.1.3.

I agree with you that the prepublish step would be ideal, but it's not really worth it to me at this point. This project still uses Grunt for God's sake!

Anyway, I hope it provides what you need. If not, there's always [`strip-bom`](https://www.npmjs.com/package/strip-bom), if that's what you're using it for, but I created this library because other BOM solutions were just not that thorough.
